GET http://localhost:5145/tasks

###
GET http://localhost:5145/tasks/1

###
POST http://localhost:5145/tasks
Content-Type: application/json

{
    "title": "Ir na academia",
    "description": "Ir para a academia a partir de semana que vem"
}