GET http://localhost:5145/tasks

###
GET http://localhost:5145/tasks/2

###
POST http://localhost:5145/tasks
Content-Type: application/json

{
    "title": "Limpar a casa.",
    "description": "Aproveitar o final de semana para limpar a casa inteira."
}

###
PUT http://localhost:5145/tasks/2
Content-Type: application/json

{
    "title": "Limpar a casa",
    "description": "Aproveitar o final de semana para limpar a casa inteira."
}

###
DELETE http://localhost:5145/tasks/3